version: '3'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: artemis
    ports:
      - 5432:5432
    networks:
      - webnet
  web:
    build: .
    depends_on:
      - db
    image: 'be_assessment:latest'
    ports:
      - '8000:8000'
    env_file:
      - env-dev.env
    volumes:
      - ../:/app
    networks:
      - webnet
networks:
  webnet:
